config/routes.rb
Rails.application.routes.draw do
  
  root "buzzs#index"
  resources :users, :except => [:edit, :index] do
  	resources :buzzs, :except => [:edit]
  end	

  get 'feed', to:"buzzs#index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create', as: 'auth'
  get 'logout', to: 'sessions#destroy', as: 'logout' 

  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  get 'searchuser', to: "users#search", as: "search_user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buzz.rb
class Buzz < ApplicationRecord
	belongs_to :user
end

app/models/follow_relationship.rb
class FollowRelationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :buzzs, dependent: :destroy

  has_many :followed_users, class_name: "FollowRelationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, through: :followed_users

  has_many :following_users, class_name: "FollowRelationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :following_users


  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :handle, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, maximum: 20 }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user
	protect_from_forgery with: :exception

	# Global helper method to get autheticated user
	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		else
			@current_user = nil
		end
	end
end

app/controllers/buzzs_controller.rb
class BuzzsController < ApplicationController

  # Before Action to get the User in defined actions
  before_action :set_user, only: [:index, :create, :destroy]

  skip_before_action :verify_authenticity_token
  
  def index
    # Redirect to Login if not logged in.
    if !current_user
      redirect_to login_url
    else
      @feed_test = {}
      current_user.followeds.each do |user|
      user.buzzs.each do |user_buzz|
          @feed_test[user_buzz] = user
        end
      end
    
      @feed_buzz = {}
      @buzz_keys = @feed_test.keys.sort_by(&:created_at).reverse
      @buzz_keys.each do |key|
        @feed_buzz[key] = @feed_test[key]
      end
    end
    
  end

  def new
    @buzz = Buzz.new
  end

  def create
    @buzz = @user.buzzs.create(buzz_params)
    respond_to do |format|
      if @buzz.save
        format.html { redirect_to feed_url, notice: 'Buzz was successfully created.' }
        format.json { render :show, status: :created, location: @buzz }
      else
        format.html { render :new }
        format.json { render json: @buzz.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @buzz = @user.buzzs.find(params[:id])
    @buzz.destroy
    respond_to do |format|
      format.html { redirect_to feed_url, notice: 'Buzz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = current_user
    end

    def buzz_params
      params.require(:buzz).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def new
    if current_user
      redirect_to feed_url
    end
  end

  def create
    print params[:email]
    print params[:password]
  	user = User.find_by_email(params[:sessions][:email])
  	if user && user.authenticate(params[:sessions][:password])
  		session[:user_id] = user.id
  		redirect_to feed_url, notice: "Logged In!"
  	else
  		flash.now[:alert] = "Invalid Credentials"
  		render 'new'
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow]
  skip_before_action :verify_authenticity_token

  def show
  end

  def new
    if current_user
      redirect_to feed_url
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def follow
    current_user.followeds << @user
    redirect_to user_path(@user)
  end

  def unfollow
    current_user.followed_users.find_by(followed_id: @user.id).destroy
    redirect_to user_path(@user)
  end

  def search
    @result = User.where("handle ILIKE ?", params[:search][:query]).first
    if @result != nil
      redirect_to user_path(@result)
    else
      redirect_to feed_path, notice: 'Not found'
    end
        
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :handle)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buzzs_helper.rb
module BuzzsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buzzs/_buzz.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <img src="https://img.icons8.com/bubbles/100/000000/user.png" alt="Image">
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <h6 >
          <strong>
            <%= link_to user_new.name, user_path(user_new)%>
          </strong> 
          <small>
            @<%= user_new.handle %>
          </small>
          <br>
          <small>
            <%= buzz.created_at.strftime("%d/%m/%Y") + " "+ buzz.created_at.strftime("%H:%M")%>
          </small>
          </h6>
          <%= buzz.content%>
        
      </div>
      <nav class="level is-mobile">
        <div class="level-left">
            
            <% if current_user.handle == user_new.handle%>
            <%= link_to 'Delete', [buzz.user, buzz], method: :delete, class: "button is-danger" %>
            <% end %>
        </div>
      </nav>
    </div>
  </article>
</div>

app/views/buzzs/_feed.html.erb
<% @buzzs.each do |buzz| %>
	<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <img src="https://bulma.io/images/placeholders/128x128.png" alt="Image">
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong>
            <%= buzz.name%>
          </strong> <small>@johnsmith</small> <small>31m</small>
          <br>
          <%= buzz.content%>
        </p>
      </div>
      <nav class="level is-mobile">
        <div class="level-left">
          <%= link_to root_path, class: "level-item" do %>
              <span class="icon"><i class="fa fa-user-circle" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to buzz, method: :delete, data: { confirm: "Are you sure you want to delete this Buzz" } do %>
                <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
            <% end %>
        </div>
      </nav>
    </div>
  </article>
</div>
<% end %>

app/views/buzzs/_followeds.html.erb
<nav class="panel is-link">
  <p class="panel-heading">
    Followed Users
  </p>
  
  <% current_user.followeds.each do |f|%>
    <a class="panel-block is-active">
    <span class="panel-icon">
      <i class="fas fa-book" aria-hidden="true"></i>
    </span>
    <%= f.name%>
  </a>
  <% end %>
  </nav>

app/views/buzzs/_form.html.erb
<div class="box">
  <%= simple_form_for([@user, @user.buzzs.build])  do |f|%>
  <%= f.error_notification %>
  <div class="field", , id="testdiv">
  <div class="control">
    <%= f.input :content,  input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Lets get Buzzing....", autofocus: true, label: false %>
  </div>
</div>
<%= f.button :submit, class: "button is-link" %>
<%end%>
</div>

app/views/buzzs/_profile.html.erb
 <nav class="panel is-link">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
        				<<img src="https://img.icons8.com/doodle/96/000000/user.png" alt="Image">
      				</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<div class="title is-6 ">
								
								<strong><h4>
									<%= link_to @user.name, user_path(@user)%>
								</h4></strong>
							</div>
							<div class="subtitle is-6">
								
								<strong>
									@<%= @user.handle%>
								</strong>
							</div>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Buzzs</p>
						<p class="title is-6"><%= current_user.buzzs.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6"><%= current_user.followeds.count %></p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6"> <%= current_user.followers.count %></p>
					</div>
				</div>
			</div>
		</div>
	</nav>

app/views/buzzs/_search.html.erb
<nav class="panel is-link">
	<p class="panel-heading ">
		Search Users
	</p>
	<%= simple_form_for :search, url: search_user_path, method: "GET" do |f| %>
	<div class="field">
            <div class="control">
                <%= f.input :query, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
            </div>
        </div>
    <div class="field">
            <div class="control">
                <%= f.button :submit, "Search", class:"button is-link is-outlined is-fullwidth" %>
            </div>
        </div>
<% end %>
</nav>

app/views/buzzs/index.html.erb
<section class="section">
	<div class="container">
		<div class="columns">
			<div class="column is-one-fifth is-narrow">
				<%= render 'profile'%>
			</div>
			
			<div class="column is-three-fifth">
				<%= render 'form'%>
					<% @feed_buzz.each do |buzz,user|%>
						
						<%= render  buzz, :user_new => user%>
					<% end %>
					
			</div>
			<div class="column is-one-fifth">
				<%= render 'search'%>
				<%= render 'followeds'%>
			</div>
		</div>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FictionBuzz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  </head>

  <body>

    <%if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice%></p>
      </div>
    <% end %>

    <%if flash[:alert] %>
      <div class="notification is-primary global-notification">
        <p class="alert"><%= alert%></p>
      </div>
    <% end %>
    <nav class="navbar is-link">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">FictionBuzz</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExample" class="navbar-menu">

    <div class="navbar-end">

      <% if current_user %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <%= link_to user_path(current_user), class: "navbar-item" do %>
            <h1 class="title is-6">Profile</h1>
          <% end %>
          
          <%= link_to logout_path, class: "navbar-item" do %>
            <h1 class="title is-6">Logout</h1>
          <% end %>
        </div>

      </div>
      <% end %>
    </div>
  </div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(@user)  do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="field">
        <div class="control">

        <div class="field">
        <div class="control">
        <%= f.input :name, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
        </div>
        </div>

        <div class="field">
        <div class="control">
        <%= f.input :email, required: true, input_html: { class:"input", type: "email" }, wrapper: false, label_html: { class:"label" } %>
        </div>
        </div>
  
          
        <div class="field">
            <div class="control">
                <%= f.input :password, required: true, input_html: { class:"input", type: "password" }, wrapper: false, label_html: { class:"label" }, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
            </div>
        </div>

        <div class="field">
        <div class="control">
        <%= f.input :handle, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
        </div>
        </div>

        <div class="field">
            <div class="control">
                <%= f.button :submit, "Sign Up", class:"button is-info is-medium" %>
            </div>
        </div>
        <% end %>

app/views/users/index.html.erb
<h1>Hello</h1>

app/views/users/new.html.erb
<div class="section">
    <div class="container has-text-centered">
    <div class="columns is-centered">

        <div class="column is-4">
            
        <h2 class="title is-2">Sign Up</h2>

        <%= render 'form', user: @user %>

        <%= link_to 'LogIn Instead', login_path %>
        </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<section class="hero">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="columns is-vcentered">
                    
                    <div class="column is-offset-1">
                        <h2 class="title has-text-black">User Profile</h2>
                        
                        <div class="box">
                            <figure class="avatar" height=200px>
                            <img src="https://img.icons8.com/doodle/96/000000/user.png"/>">
                        </figure>
                        <h3 class="title">
                            <strong><%= @user.name%></strong>
                        </h3>
                        <h4 class="subtitle">
                            <strong>@<%= @user.handle%></strong>
                        </h4>
                        <% if current_user == @user %>
                            <h6 class="subtitle is-link">
                                <strong>No Need to follow yourself</strong>
                            </h6>
                        <% elsif current_user.followeds.include?(@user)%>
                            <%= link_to 'UnFollow', unfollow_user_path(@user), method: :post, class: "button is-danger is-rounded" %>
                        <% else %>
                            <%= link_to 'Follow', follow_user_path(@user), method: :post, class: "button is-link is-rounded" %>
                        <% end %>
                        </div>

                        <h4 class="title is-2">
                            <strong>Tweets</strong>
                        </h4>
                        <div>
                            <% sorted_buzz = @user.buzzs.sort_by { |st| st.created_at }.reverse %>
                            
                            <%= render  sorted_buzz, :user_new => @user%>

                        </div>

                        
                    </div>
                </div>
            </div>
        </div>
    </section>